export const constantStorage = {
  CURRENT_ACTIVE_STEP: "CURRENT_ACTIVE_STEP",
  SIDEBAR_VISIBLE: "SIDEBAR_VISIBLE",
  ITINERARY_CURRENT_SELECTED_DAY: "ITINERARY_CURRENT_SELECTED_DAY",
  ITINERARY_CURRENT_ACTIVITY: "ITINERARY_CURRENT_ACTIVITY",
};
