export const constantStorage = {
  CURRENT_ACTIVE_STEP: "CURRENT_ACTIVE_STEP",
  SIDEBAR_VISIBLE: "SIDEBAR_VISIBLE",
  ITINERARY_CURRENT_SELECTED_DAY: "ITINERARY_CURRENT_SELECTED_DAY",
  ITINERARY_CURRENT_ACTIVITY: "ITINERARY_CURRENT_ACTIVITY",
  ITIERARY_INDIRECT_COST_MARGIN: "ITIERARY_INDIRECT_COST_MARGIN",

  CURRENT_ROUTE: "CURRENT_ROUTE",
  CLIENTS_PAGINATION: "CLIENTS_PAGINATION",
  PARTNERS_PAGINATION: "PARTNERS_PAGINATION",
  QUOTATION_PAGINATION: "QUOTATION_PAGINATION",
  RESERVATION_PAGINATION: "RESERVATION_PAGINATION",
  SERVICES_PAGINATION: "SERVICES_PAGINATION",
  USERS_PAGINATION: "USERS_PAGINATION",
};
